### ISSUE TITLE
Zend only?

### ISSUE THREAD

**Issue by hailwood** [Ecodev/graphql-upload#1]
So just checking, this middleware only works with the zend framework?

Would you be interested in turning this package into a generic repository for graphql upload middlewares, e.g. I could create a `LaravelUploadMiddleware`?

**Comment by PowerKiKi** [comment]
Not at all, it implements the recently accepted PSR-15 and can thus be used with anything that follow that specification. The README instructions are only an example of one framework, because we don't really want to duplicate docs for every single framework out there. But you could use it with pretty much anything.

**Comment by hailwood** [comment]
Gotcha,

Just for completion purposes, if someone were to use this package with Laravel, as it does not implement the PSR-15 spec currently, we need to use a bridge package.

I recommend https://github.com/jshannon63/laravel-psr15-middleware, the docs are fairly explicit on how to use it.

--
Matt
