### ISSUE TITLE
Make v5 allow PHP 8

### ISSUE THREAD

**Issue by svnldwg** [Ecodev/graphql-upload#17]
Hey, I recently stumbled across this and project and I am using it and loving it, thanks for the great work!

I am using it in conjunction with PHP 8 and thecodingmachine/graphqlite.

graphqlite has a requirement for webonyx/graphql-php ^v0.13.4 (https://github.com/thecodingmachine/graphqlite/blob/master/composer.json#L14).

graphql-upload v6 requires webonyx/graphql-php ^14. 

Therefore currently I can only use graphql-upload v5 together with graphqlite. But graqhl-upload v5 does not support PHP 8, so it is impossible to use graphql-php in my setup. That is why I created a fork and tagged a 5.0.1 which allows PHP 8.

This is all I had to do: https://github.com/svnldwg-forks/graphql-upload/commit/57b5d835b89a7bebe7443714ecf4168bb128f3d9

It works, but I would love to get rid of my fork and just use the original project. Could you allow PHP 8 for v5?

**Comment by PowerKiKi** [comment]
I'm surprised to learn that you use both libraries together. I'm not familiar with `thecodingmachine/graphqlite`, but was under the impression that it would be more of a replacement  to `ecodev/graphql-upload`, rather than a complement.

But anyway, unfortunately we don't support past versions. And even though this particular change seems small, I am not willing to introduce a precedent by accepting this change.

Instead I would suggest to push for an update of  `thecodingmachine/graphqlite`. It seems they are willing to do it and would [accept help for it](https://github.com/thecodingmachine/graphqlite/issues/283#issuecomment-681811389). There is also an opened PR for it: https://github.com/thecodingmachine/graphqlite/pull/327

**Comment by svnldwg** [comment]
Thanks for your reply, I understand.

Yes, `thecodingmachine/graphqlite` relies on your package for file uploads. It is documented here: https://graphqlite.thecodingmachine.io/docs/file-uploads

**Comment by PowerKiKi** [comment]
Oh my bad, I thought we were talking about `ecodev/graphql-doctrine` :roll_eyes:  , which _is_ a replacement to `thecodingmachine/graphqlite`. But `ecodev/graphql-upload` totally make sense to be used with `thecodingmachine/graphqlite`.
